### ISSUE TITLE
🗨️ [Enhancement] Enabling GitHub Discussions for In-Depth Conversations

### ISSUE THREAD

**Issue by Martinligabue** [netrisdotme/netris#50]
I think Github Discussions should be enabled to allow people to talk about some suggestions without having to use the Issues section.
I think it serves a different purpose than the Discord server, as it can be used for real-time support, while discussions would be useful for longer conversations that might also be helpful to other users when they are resolved.
Also, the discussions would be "closer" to the code, so it would be more about the code, whereas Discord would be more for the users.

**Comment by wanjohiryan** [comment]
Absolutely, that's a great suggestion.

Github discussions have now been enabled.
