### ISSUE TITLE
Hotel version

### ISSUE THREAD

**Issue by mitcoes** [netrisdotme/netris#52]
In collaboration with Steam, I think it would be a great feature to be able to provide hotels to add a bluetooth controller to their Smart TVs and be able to play some games from Steam, being a platform for hotels to give a service, and to Steam to advertise new games, or just to allow their own customers to use their games without a Steam Deck or another computer when staying at a hotel room more than expected, to kill some time.

**Comment by wanjohiryan** [comment]
Hey @mitcoes 

Sorry, I did not get your point. 

Could you please be more specific? And how can i help?
