### ISSUE TITLE
🧑🏽‍🧑🏾‍🧒🏾 [Sharing] Potential Issue Regarding Steam library Sharing

### ISSUE THREAD

**Issue by Dekomoro** [netrisdotme/netris#58]
Steam family sharing will be completely changed soon to be nation and account based rather than device based.

If this feature relies on that, it may not be worth advertising as it will grow obsolete in the near future.
![image](https://github.com/netrisdotme/netris/assets/62639738/ac36ed44-d819-4d4e-b917-7a8bd0fa944b)

**Comment by Dekomoro** [comment]
Love the work you guys are doing btw, I sent in an order for netris prime.

**Comment by wanjohiryan** [comment]
Hey, 

This might not pose an issue, probably on the licensing side of things.

We plan to utilise your "machine" and give your friend(s) temporary access to it.

It will be like borrowing your steamdeck, but this time it is in the clouds, and my game progress won't affect yours.

PS: this might be a legal nightmare, hopefully it won't get to that.
