### ISSUE TITLE
Docker Setup

### ISSUE THREAD

**Issue by itguy327** [netrisdotme/netris#60]
Project looks amazing and I'm super eager to test out in a self hosted model. Are there instructions for getting this running in Docker?

Thank you for your work

**Comment by AppStudioLB** [comment]
Me too, I’m also waiting for the instructions. When I asked in the Discord channel, they said we should wait until pull request #43.

**Comment by itguy327** [comment]
Thanks. Totally can't wait lol, I've been trying so many other solutions
and this has the most promise

**Comment by dennyjoe** [comment]
Yes, I'm excited about this too.

**Comment by wanjohiryan** [comment]
Hey, v0.2 is out... you should definitely check it out.

Tell me how it goes 😉
